# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: andrew_chaa
google_analytics: dbyll
title: Andrew Chaa

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Andrew Chaa

description: Stylish Jekyll Theme
author:
  name: Andrew Chaa
  email: andrew.yh.chaa@gmail.com
  github: andrewchaa
  twitter: andrewchaa
  # pinterest: asd123
  linkedin: andrewchaa
  bio: another day, another PR
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
